version: 2

# Sources
sources:
  - name: raw_data
    description: 'Database to storage the raw data'
    database: DEV
    schema: RAW
    tables:
      - name: customers
      - name: orders
      - name: payments

# Models
models:
- name: raw_customers
  description: Raw data customers.

- name: raw_orders
  description: Raw data orders.

- name: raw_payments
  description: Raw data payments.